name: Keep Alive

on:
  schedule:
    - cron: 0 * * * *

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Alive
        run: |
          curl -s -o /dev/null https://silver-space-zebra-q795jgp6gqq4249pg.github.dev/
